name: Android CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v3
      - name: Lint Android
        run: ./gradlew lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v3
      - name: Build
        run: ./gradlew app:assemble
      - uses: actions/upload-artifact@v4
        with:
          name: fdroid-release-apk
          path: app/build/outputs/apk/fdroid/release/app-fdroid-release.apk
      - uses: actions/upload-artifact@v4
        with:
          name: normal-release-apk
          path: app/build/outputs/apk/normal/release/app-normal-release.apk
