name: GitHub Release CI

on:
  push:
    tags: [ '*' ]

env:
  SIGNING_KEYSTORE_GITHUB: ${{ secrets.SIGNING_KEYSTORE_GITHUB }}
  SIGNING_PROPERTIES_GITHUB: ${{ secrets.SIGNING_PROPERTIES_GITHUB }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v3
      - name: Setup Signing
        run: ./ci_signing_setup.sh
      - name: Build
        run: ./gradlew app:assemble
      - name: Github Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: |
            app/build/outputs/apk/fdroid/release/app-fdroid-release.apk
            app/build/outputs/apk/normal/release/app-normal-release.apk
